# Generated by Django 4.1.4 on 2022-12-27 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("showtimes", "0001_initial"),
        ("m_users", "0001_initial"),
        ("theaters", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TheaterTicket",
            fields=[
                (
                    "theater_ticket_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
                (
                    "multiplex_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="m_users.muser"
                    ),
                ),
                (
                    "showtime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="showtimes.showtime",
                    ),
                ),
                (
                    "theater",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="theaters.theater",
                    ),
                ),
            ],
            options={
                "db_table": "multiplex_theater_tickets",
            },
        ),
    ]
